project_id = "gkomblopvuaxtenzjoni"

[functions.twilio-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.elevenlabs-agent]
verify_jwt = false

[functions.get-twilio-calls]
verify_jwt = true
