project_id = "ppfynksalwrdqhyrxqzs"

[functions.twilio-webhook]
verify_jwt = false

[functions.create-checkout-with-trial]
verify_jwt = false

[functions.send-trial-reminder]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
